In [72]:
import numpy as np
import pandas as pd

**Task 1**
Creating a numpy array

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10]) #create an array
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


**Task 2** Creating a array of size (7,6), reshape to (3,4)

In [4]:
arr = np.random.randint(30, size=(7,6)) #random integers upto 30
print(arr)

[[ 3 18 25 19 16  5]
 [20 23  0 23 26 21]
 [18 19  0 24  9 11]
 [ 0  7 12 11 14  5]
 [21  1 25  0 12 10]
 [14 15 16 26 11 27]
 [ 1 10  6 20 23  2]]


In [7]:
arr = arr.reshape(3, 14) #changing shape of a matrix
print(arr)

[[ 3 18 25 19 16  5 20 23  0 23 26 21 18 19]
 [ 0 24  9 11  0  7 12 11 14  5 21  1 25  0]
 [12 10 14 15 16 26 11 27  1 10  6 20 23  2]]


**Task 3** Extract odd numbers from an array

In [13]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
odd = arr[arr%2 != 0] #Only those values which fulfils a certain condition
print(odd)

[1 3 5 7 9]


**Task 4** Make all odd numbers to -1 of the previous array

In [14]:
arr[arr%2 !=0] = -1 # Set values to -1 which fulfils a specific condition
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


**Task 5** Make odd numbers to -1 without affecting original array

In [21]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
out = np.array(arr)
out[out%2 != 0] = -1

print(out)
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]
[ 1  2  3  4  5  6  7  8  9 10]


**Task 6** Positions where elements of two array matches

In [25]:
a = np.array([1,2,3, 2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.where(a==b)) #np.where returns indices instead of values

(array([1, 3, 5, 7]),)


**Task 7** Get all the items between 5 and 10 from array

In [31]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[(a>=5) & (a<=10)]) # Using conditionals to return values

[ 6  9 10]


**Task 8**

In [49]:
a = np.zeros((10,1)) # Create vector of 0s
b = np.ones((10,1)) # Create vector of only 1s

c = np.concatenate((a,b)) # Merge these two vectors

a = a.reshape((1,10))
b = b.reshape((1,10))

d = np.concatenate((a,b), axis=1)

print(c)
print(d)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Task 9**

In [56]:
arr = np.random.randint(20, size=(5,4)) # Random numbers upto 20

print(arr)

[[15  8  2 13]
 [ 5  9  5 14]
 [18  1 17  4]
 [11 12 18 15]
 [16  6 11  6]]


**Task 10**

In [58]:
n_samples = 5
n_features = 4

x = np.random.rand(n_samples, n_features)
y= np.random.randint(0, 2, n_samples)

print('x = ', x)
print('y = ', y)

x =  [[0.85073446 0.59045558 0.43225619 0.28739913]
 [0.19347084 0.72141075 0.14461338 0.92385652]
 [0.69558492 0.27385302 0.64470238 0.30709304]
 [0.91080484 0.54285877 0.18983894 0.35646871]
 [0.90988524 0.43007488 0.60326433 0.82517265]]
y =  [1 0 0 1 1]


**Task 11**

In [88]:
def extract_subset(x, y, y0):
  return x[y == y0]   # Extract rows of same indices which matches y with y0

print(extract_subset(x,y,0))

[[0.19347084 0.72141075 0.14461338 0.92385652]
 [0.69558492 0.27385302 0.64470238 0.30709304]]


**Task 12**

In [96]:
url = "https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv"
data = np.genfromtxt(url, delimiter=",", skip_header=1)
data

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [5.4, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, 0.1, nan],
       [5.4, 3.7, 1.5, 0.2, nan],
       [4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3. , 1.4, 0.1, nan],
       [4.3, 3. , 1.1, 0.1, nan],
       [5.8, 4. , 1.2, 0.2, nan],
       [5.7, 4.4, 1.5, 0.4, nan],
       [5.4, 3.9, 1.3, 0.4, nan],
       [5.1, 3.5, 1.4, 0.3, nan],
       [5.7, 3.8, 1.7, 0.3, nan],
       [5.1, 3.8, 1.5, 0.3, nan],
       [5.4, 3.4, 1.7, 0.2, nan],
       [5.1, 3.7, 1.5, 0.4, nan],
       [4.6, 3.6, 1. , 0.2, nan],
       [5.1, 3.3, 1.7, 0.5, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [5. , 3. , 1.6, 0.2, nan],
       [5. , 3.4, 1.6, 0.4, nan],
       [5.2, 3.5, 1.5, 0.2, nan],
       [5.2, 3.4, 1.4, 0.2, nan],
       [4.7, 3

In [97]:
column = data[:, 0]
mean = np.mean(column)  # Command for mean
median = np.median(column) # Command for median
standard_deviation = np.std(column) # Command for standard deviation
print(mean)
print(median)
print(standard_deviation)

5.843333333333334
5.8
0.8253012917851409
